Disable Netty error logs in UtpTestResultListenerServerRunner
This commit disables Netty error logs to prevent `NoClassDefFoundError`
when running connectedAndroidTest. The
`UtpTestResultListenerServerRunner` now sets a default
`JdkLoggerFactory` with logging level set to `Level.OFF` for Netty's
internal logging.

A regression test has been added to `UtpTestBase` to verify that
`java.lang.NoClassDefFoundError` is not outputted during repeated runs
of `connectedAndroidTest`.

Test: connectedAndroidTestDoesNotOutputNoClassDefFoundError
Fixes: 466374462
Change-Id: Ia8d6bd18c1243ad6da3e1d76855228889baa9845