Revert "Fix tests that needs files from resources in jars"
Build errors:
VmTraceParserTest.java:351:
cannot find symbol
return TestResources.getFile(getClass(), path);

This reverts commit 08e107ff0b6979f2915ed25ce6cae77352288a1b.

Change-Id: I4b7e4a18745347ed0f4f76dc3818a4b32c1d1833