Output sensible error message on build command failure.
So we get something like:

> Build command failed.
  Error while executing...

instead of

> com.android.ide.common.process.ProcessException: Error while...

Change-Id: Ica0d04d718be2a91530cf78377477dc0704e513a