Fix NoClassDefFoundError with Gradle 4.3 or earlier (again).
This bug was fixed in commit d083c8855cc840641c7d1b6310532999fa4a2df0,
but reappeared after commit 9a263891f1ea28a5a4ace46aadb20af7cced69ee:
AppPlugin references the new ModelBuilder, making build or sync fail
on older Gradle versions before the plugin can run a version check to
provide a message asking users to update their Gradle version.

This fix slightly decreases code design, but hopefully it's still
acceptable.

Fixes: 73383831
Test: New GradleVersionCheckTest
Change-Id: Ic625489c6121921a6a850f546afaa217a8afc1a0