Avoid breaking sync when adding a new boolean flag
Gradle tooling API throws an error when trying to proxy an enum value
that is not present on the Studio side, and in this case it would be
preferable to simply ignore the values that Studio doesn't know about.

This allows us to add a new boolean value to the Android Gradle Plugin
without breaking sync in older versions of Studio that do not know about
that boolean value (e.g. a previous canary)

This is only implemented for model v2, as that is the future and doesn't
introduce any compatibility constraints at this point, but could be
backported if we think that would be useful.

The stacktrace from adding a new value is of the form:

java.lang.IllegalArgumentException: Cannot convert string value 'UNIFIED_TEST_PLATFORM' to an enum value of type 'com.android.builder.model.AndroidGradlePluginProjectFlags$BooleanFlag' (valid case insensitive values: APPLICATION_R_CLASS_CONSTANT_IDS, TEST_R_CLASS_CONSTANT_IDS, TRANSITIVE_R_CLASS, JETPACK_COMPOSE, ML_MODEL_BINDING)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter.toEnum(ProtocolToModelAdapter.java:204)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter.adaptToEnum(ProtocolToModelAdapter.java:177)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter.createView(ProtocolToModelAdapter.java:146)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter.convert(ProtocolToModelAdapter.java:276)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter.convertMap(ProtocolToModelAdapter.java:284)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter.convert(ProtocolToModelAdapter.java:267)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter.access$1500(ProtocolToModelAdapter.java:56)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter$AdaptingMethodInvoker.invoke(ProtocolToModelAdapter.java:477)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter$PropertyCachingMethodInvoker.invoke(ProtocolToModelAdapter.java:705)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter$SafeMethodInvoker.invoke(ProtocolToModelAdapter.java:742)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter$SupportedPropertyInvoker.invoke(ProtocolToModelAdapter.java:766)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter$InvocationHandlerImpl.invoke(ProtocolToModelAdapter.java:432)
	at com.sun.proxy.$Proxy149.getBooleanFlagMap(Unknown Source)
	at com.android.tools.idea.gradle.project.sync.ModelCacheV1ImplKt.modelCacheV1Impl$androidProjectFrom(ModelCacheV1Impl.kt:1092)

Bug: 202282920
Test: Exisiting regression tests
Change-Id: I4100bdb765981e056241c00d157113a2e3870e66