Make it an error to have too-low minSdk starting with r26
Starting with NDK r26, it will now be a build error for minSdk from build.gradle to be less than the minimum supported by the current NDK.

The user may suppress the error by passing a flag at the Gradle command-line:

	-P:android.ndk.suppressMinSdkVersionError=19

The value passed in must match android.<config>.minSdk to work. This restriction forces the user to update the flag when they update to an NDK that increases min SDK version

New error emitted when minSdk is set too low for r26+ NDK:
error: Platform version 19 is unsupported by this NDK. Please change minSdk to at least 21 to avoid undefined behavior.
To suppress this error, add android.ndk.suppressMinSdkVersionError=19 to the project's gradle.properties.

New warning emitted when minSdk is set too low for pre-r26 NDK:
warning: Platform version 13 is unsupported by this NDK, using 14 instead. Please change minSdk to at least 14 to avoid this warning.

Bug: 310718265
Test: Added unittests
Change-Id: If0579edb8e4ba952b600e33afbb1b825944e0b83